/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste.gradle.lib;

public class LibGradle {
    public void someLibraryMethod() {
        System.out.println("Isso é um teste2");
    }
}
