/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste.gradle.lib;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        LibGradle classUnderTest = new LibGradle();
    }
}
