/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package teste.gradle;

import teste.gradle.lib.LibGradle;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	//Produto produto = new Produto("vad", 1);
		LibGradle lib = new LibGradle();
		lib.someLibraryMethod();
		//System.out.println(produto.getNome());
	}
}
